### ISSUE TITLE
Input box

### ISSUE THREAD

**Issue by ktb92677** [vurtun/zahnrad#19]
Hey! The input box is still not working quite right, am I doing something wrong or has that not yet been perfected? In specific I cannot select my own index in the input box an make modifications. I am using the windows example. Thanks for taking a look!

**Comment by ktb92677** [comment]
I'm sorry, I spoke far too soon. It works just fine now!

A nice feature through in the input box might be an enter action (similar to how the button has an if statement to handle a click action).

**Comment by ktb92677** [comment]
Okay, I've been able to pin point that input box issue that I mentioned above. When you use the arrow keys to navigate through a text field the index gets messed up somewhere and it starts adding random characters in random spots. So yes this is still an issue.

Also do you have any plans on implementing the following:

Text fields (similar to note pad)
Spread sheets (similar to excel)

Thanks!

**Comment by vurtun** [comment]
Hey,
1.) Bug
I am not able to replicate your bug. I tried indexing by mouse clicking and array key movement and everything seems fine. Did you have any special input that I can test to replicate the problem?

2.) Enter event handling
It is extremely easy to add it yourself. You just have to check if the edit box is active and the enter key was pressed :
```c
 zr_editbox(context, &editbox);
if (editbox.active && zr_input_is_key_pressed(input, ZR_KEY_ENTER)) {
    /* event handling */
}
```
3.) Text fields
I assume you mean multi-line editboxes. The biggest problem is that it extremely hard to implement text input. The editbox is probably the most complex part inside the library and is based on a single line. So a text field would be way more complex. The problem thereby lies in the data structure. At the moment I use a single buffer for text manipulation, while actual text editing needs more complex data structures (at the minimum two buffers). But at that point I would already implement a text editor. That being said I could take a look at stb_textedit.h and check how far I can go with it.

4.) Spread sheets
Spread sheets are easy to implement and don't need any special functionality. What you do is something similar to what I do in the node editor example. Allocate a big space inside the window and draw a grid inside the space. If the user clicks inside a cell you draw an editbox directly at the position and provide user input. After that you draw the input inside the cell.
If you want then I could implement an example to showcase what I mean.

**Comment by ktb92677** [comment]
1. + 2. Thanks for both of these notes, as you may have guessed these issues have been resolved.

As for the input box, how is that going? Do you think it could be done?

And the spread sheet ya, could you draw up a quick example?

Again, thank you SO much for all of your work here, honestly it's phenomenal!

**Comment by vurtun** [comment]
Hey,
1.) Input box
I thought about it and decided that for version 1.0, which I am currently trying to get this library into shape for, will not have it. The reason mainly is that I have no idea how much work it would take to write it. So instead I am currently trying to focus on removing all bugs for the first release version and stay away from new sources of bugs for now. If I will work on it after the first release is still in the air since I want to spend some time on another more time intensive project and probably need some time away to see things differently.

2.) Spread sheet
I will definitely tackle the spread sheet example but at the moment there are to many small last minute changes and bugs to fix.

**Comment by ktb92677** [comment]
Thanks for the attention! I am a little upset to hear about the input box, when do you think it would be possible to put this in? I could help you out if you wanted!

**Comment by vurtun** [comment]
OK I took another look at my `zr_edit` + utility code and decided I will give the input box a try on saturday. I already provide most of the needed functionality, the only thing that is missing is multi-line text selection. Some parts are even easier since I do not have to support text that goes over the bounds of the box. On the other hand it probably needs a scrollbar but that hopefully should be manageable. If I can make good progress on saturday then I will finish it otherwise I will leave it be.

**Comment by vurtun** [comment]
Hey,
quick update. I will probably not be able to finish it today but I got most of it working. The only
thing left is to remove some bugs and add support for `'\n'` inside the input box. Also found and removed some additional bugs so I will definitely finish it and push it ASAP.

**Comment by ktb92677** [comment]
Wow! Thanks a bunch for the update. This'll help out a lot!

Another feature that would be real nice is syntax highlighting for the text box. Like I could give you an array of strings and a corresponding color they should show up as. Do you think this can be done too?

**Comment by vurtun** [comment]
Please don't tell me you are planning on using it for a text editor. If you want to have a text editor you should really write your own and look for data structures for text editors. What I wrote is OK and should work nicely for most basic needs but not for editing lots of text. I mean a lot would probably work but it is inherently not optimized for lots of text. Also syntax highlighting is not what a basic edit box should have or what I would want to add into the core library since it is to specific. But I guess it should be possible to add it yourself if you really want it.

**Comment by dumblob** [comment]
>Also syntax highlighting is not what a basic edit box should have or what I would want to add into the core library since it is to specific. But I guess it should be possible to add it yourself if you really want it.

+1
