### ISSUE TITLE
Demo Makefile Won't Build Demo

### ISSUE THREAD

**Issue by CaptainKraft** [vurtun/zahnrad#20]
The demo Makefile tries to use "MakefileDebug" which doesn't exist. There is a "Makefile" for each platform rather than a "MakefileDebug" file.

**Comment by vurtun** [comment]
Hey thanks for your feedback, that particular Makefile was actually not supposed to be there since each Demo has its own Makefile for compiling, so I removed it. Having a global Makefile outside of debugging purposes does not make sense since you simple cannot compile every demo at once (Linux and Windows version).

**Comment by CaptainKraft** [comment]
Thanks for the quick reply! That makes more sense than what I tried to do haha.
