### ISSUE TITLE
zr_layout_row issues

### ISSUE THREAD

**Issue by ktb92677** [vurtun/zahnrad#22]
Hey! So I was using "zr_layout_row_space_begin" and "...end" today and I noticed that the scroll bar that is added is incorrect. I want to add like a sub-section in the window where the scroll bar is in the middle of the window. I'm trying to add lots of data to the window but I don't want the entire window to scroll down I just want a certain portion of it it (hopefully that makes sense).

As usual thanks for the support!

**Comment by vurtun** [comment]
Hey,
>  I want to add like a sub-section in the window where the scroll bar is in the middle of the window  

Sounds interesting but could you describe what you are doing exactly (maybe post a minimal snippet with only the library function calls). So far what I understood is that the combination of free space layouts and scrollbars is bugged. Or is the scrollbar bugged for the sub-section, or even both?

**Comment by ktb92677** [comment]
The scroll bar for the subsection is bugged. I am currently mobile but let me know if that's enough information.

**Comment by vurtun** [comment]
I have not much to go on, so a code snippet would be nice. Other than that under normal circumstance the only reason I know at the moment why a scrollbar does not work for groups is if the scrollbar `struct zr_vec2` is not persistent or not correctly used. If that was not the problem than please provide me with more information, so that I test myself.
