### ISSUE TITLE
Password Hiding

### ISSUE THREAD

**Issue by stfacs** [vurtun/zahnrad#28]
Hi, is there is a way to hide text input as you type it in, in the same way when you enter passwords when logging into a website (for example)? If not, could you make a feature for this, or explain how one would make/do one? 
Thanks a lot!

**Comment by vurtun** [comment]
Hey,
thanks for your feedback. I was not sure if it is possible but I had an idea so I tested it out
and it seems to work. But for this to work you have to use `zr_edit` and not provide a
cursor by just passing `NULL`. The more complex `zr_edit_box` and `zr_edit_field` do not work
since the modification between frames is not extractable outside the function.
In addition you have to provide an additional buffer with the same size to copy the
placeholder symbol into (this can be any character you want even unicode characters like `⚫`)
After the box was updated you just have to check for the changes and if anything was added just
add it to your password buffer.

```c
/* frame persistent data */
static char password[64];
static size_t length;
static int active;

/* password edit */
size_t i = 0;
char buffer[16];
size_t old_len = length;
for (i = 0; i < length; ++i) buffer[i] = '*';
zr_edit(&layout, password, &length, 64, &active, NULL, ZR_INPUT_DEFAULT);
if (old_len < length)
    memcpy(&password[old_len], &buffer[old_len], length - old_len);
```

**Comment by stfacs** [comment]
Thank you so much for the reply! It helped a lot, I was able to use your example and adapt it and get it to work! Thanks again

**Comment by vurtun** [comment]
Glad that I could help. I will close the issue then.
