### ISSUE TITLE
MacOS build failed

### ISSUE THREAD

**Issue by rumkin** [vurtun/zahnrad#31]
MacOS demos build failing with:

```
demo.c:32:10: fatal error: 'GL/glew.h' file not found
#include <GL/glew.h>
```

**Comment by vurtun** [comment]
Thanks for your issue. I will look into it as soon as I have this rewrite done.

**Comment by richi** [comment]
I have put together an an experimental (native)  Cocoa / OpenGL render backend, including a (working) Xcode project. Have a look at:

https://github.com/richi/MacZahnrad

It should compile on all 64 bit machines. 32 bit will probably do it as well, as long as there is at least OpenGL 3.2. 

As always, everything runs smooth on my machines, but of course more testing is needed!

A Metal version for MacOS, iOS and tvOS is in the making.

Cheers, richi

**Comment by vurtun** [comment]
Woah great work.
I never had a Mac or any Apple product so I don't have experience and the possibility to work with ObjC, MacOS, iOS and tvOS so this is absolutely great.

> As always, everything runs smooth on my machines, but of course more testing is needed!

This should more than suffice for most and provide a perfect starting point for others.

> A Metal version for MacOS, iOS and tvOS is in the making.
That would be absolutely fantastic and cover all Apple related needs for this library.

Finally do you want to keep it in your repository and I just add a reference to it or do you want to create a pull request and add into this repository?

**Comment by richi** [comment]
> Finally do you want to keep it in your repository and I just add a reference to it or do you want to create a pull request and add into this repository?

I would suggest first doing this and later on doing that :)

If you could include a reference to it for a few days until we get one or two additional volunteers to test things, I would later on create a pull request. What do you you think?

**Comment by vurtun** [comment]
In my opinion it already looks good enough that you can create a pull request. The chance that somebody will find, use and maybe even propose a fix for a bug he finds is probably way higher if it is located in the main library. In addition most of the time anyone who is able to use this library is probably experienced enough to fix small issues.

**Comment by richi** [comment]
OK! Right now I am working on a combined version using OpenGL on the Mac and OpenGL ES on iOS / tvOS (a friend of mine requested it). As soon as the OpenGL ES part is done  I will create the pull request. This will give us three version for the price of one :+1:

**Comment by richi** [comment]
The pull request is created! Let the games begin...

**Comment by vurtun** [comment]
Pull request is accepted and the demos are now part of zahnrad. I tried to read through and understand the demos but since I am not used to ObjC it is not as easy, especially since it is platform interaction code. But as far as I can tell it is quite a feat with all systems inside one general code base with additional defines for touch interface. What I did not find out are the demos based on a real time loop or event based?

**Comment by richi** [comment]
By default, OS X and tvOS are running on a real time loop, iOS does the UI part event based. But it is all easy to change. The defines are in ZahradBackend.h

* ZR_REFRESH_ON_EVENT_ONLY
updates the UI event based

* ZR_TOUCH_SCREEN
handles events in touch screen mode

* SIMULATE_TOUCH
allows to simulate a touch screen on OS X or tvOS

The platform specific code is in the main.m files. The objc class ZahnradBackend contains the common code. You might find the method drawFrameWithScale:width:height: (device_draw) interesting, since it caches the VBOs on demand. This makes it possible to run the game logic asynchronously to the ui logic. Let's say the game runs with 60 fps but the ui refresh happens only with 10 fps or even more lazy, only in case of an event. Thanks to your clear and minimalistic design in zahnrad, this was actually not difficult at all.
