### ISSUE TITLE
Bug: possible call to free() on unallocated memory

### ISSUE THREAD

**Issue by dumblob** [vurtun/zahnrad#35]
Shouldn't the `zr_tooltip_end()` call be rather only in case some tooltip was created? In
~~~~
    /* execute tooltip and fill with text */
    if (zr_tooltip_begin(ctx, &layout, (float)text_width)) {
        zr_layout_row_dynamic(ctx, (float)text_height, 1);
        zr_text(ctx, text, text_len, ZR_TEXT_LEFT);
    }
    zr_tooltip_end(ctx);
~~~~
it seems to be quite dagerous. Solution might look like the following:
~~~~
    /* execute tooltip and fill with text */
    if (zr_tooltip_begin(ctx, &layout, (float)text_width)) {
        zr_layout_row_dynamic(ctx, (float)text_height, 1);
        zr_text(ctx, text, text_len, ZR_TEXT_LEFT);
        zr_tooltip_end(ctx);
    }
~~~~
I didn't check other similar places, but it's worth taking a careful look at.

**Comment by vurtun** [comment]
OK this one is a little bit complex. In theory nothing can go wrong with my old version, since `zr_popup_begin` will always return `true`, given that the correct argument are passed. Even worse yesterdays version needed the old version or it would not work. But I fixed popups today and now you are right. There were no real bad consequences for the old version since nothing really has to be freed since I have garbage collector inside `zr_clear` but I think since all other non-blocking popups, tree layout and groups has this style it is probably the best to keep everything in one format (except `zr_begin` and `zr_end`).
