### ISSUE TITLE
Endless loop in zr_user_font_glyphs_fitting_in_space

### ISSUE THREAD

**Issue by richi** [vurtun/zahnrad#36]
I have found a small glitch in zr_user_font_glyphs_fitting_in_space. It is easy to run into an endless loop, since glyph_len can get zero and there is no test for that in:

         while ((width <= space) && text_len) { 

I guess it should read:

        while ((width <= space) && text_en && glyph_len) {

Another problem can occur if offset is not getting incremented and the function therefore returns 0. This will result in an endless loop  for example in zr_widget_edit_box.

Really great work!

Cheers, richi

**Comment by vurtun** [comment]
Hey,
thanks for issuing the bug. I actually removed `glyph_len` in the condition some time ago because it broke `zr_edit_field` but hopefully fixed the issue now by resubmitting and tweaking  `zr_edit_field` and `zr_edit_box`. Great find by the way the text input functions are not really nice to read since the problem on hand is quite complex and not really easy to divide into sub problems/functions.
