### ISSUE TITLE
Compiling with Clang LLVM ILP32 / LP64 

### ISSUE THREAD

**Issue by richi** [vurtun/zahnrad#38]
Right now, compiling with Clang LLVM in 32 or 64 bit gives some minor type issues.

--
`ZR_COMPILE_WITH_FIXED_TYPES 1`

ILP32: `zr__check_size` failed.

LP64:
a lot of warnings (demo.c) because  size_t* ('unsigned long * ') is incompatible to zr_size* ('unsigned long long *'). (stupid compiler...)

changing: 

    typedef uint64_t zr_size;

to:

    typedef uintptr_t zr_size;

would solve 32 and 64 bit issues.
   
--
`ZR_COMPILE_WITH_FIXED_TYPES 0`

ILP32:
`zr__check_ulong` failed.

LP64:
No problems.

changing: 

    typedef unsigned long zr_ulong;

to:

    typedef unsigned long long zr_ulong;

would solve 32 bit issues, without generating 64 bit ones :)

Cheers, richi

**Comment by vurtun** [comment]
Hey and thanks, 
`typedef uint64_t zr_size` was definitely a mistake for `ZR_COMPILE_WITH_FIXED_TYPES 1` and I fixed it. `zr_ulong` for `ZR_COMPILE_WITH_FIXED_TYPES 0` is a completely different beast. The problem is that I cannot use `unsigned long long` for `zr_ulong` since I use C89 and `unsigned long long` was defined in C99. That is the reason why I have `ZR_COMPILE_WITH_FIXED_TYPES` with size checks. To provide default values if possible and otherwise let the user define the correct one. But as far as I can see, it is probably possible to remove `zr_ulong` and maybe `double` as well to hopefully solve the issue at least for 32-bit and 64-bit systems.
