### ISSUE TITLE
Simple zahnrad Tutorial

### ISSUE THREAD

**Issue by krakenrad** [vurtun/zahnrad#49]
Hi vurtun. You just direct messaged me (Krakenrad2) on twitter about using github to contact you.

I'll be brief:
-Right now I'm drawing my GUI to the SDL surface of my window (rendering text, bitmap buttons, mouse events, etc...)
-I would rather use zahnrad but the examples in the demo folder are *very* long.
-A simple tutorial on making the simple example below work in SDL would be good.
-I could make one, but I'm guessing it requires much more code to make it work with SDL.

Could you give me some general advice about what I should focus on to make the example below work in SDL?

Thanks.

Copy And Pasted Code:
-----------------------------
/* init gui state */
struct zr_context ctx;
zr_init_fixed(&ctx, calloc(1, MAX_MEMORY), MAX_MEMORY, &font);

enum {EASY, HARD};
int op = EASY;
float value = 0.6f;
int i =  20;

struct zr_layout layout;
zr_begin(&ctx, &layout, "Show", zr_rect(50, 50, 220, 220),
    ZR_WINDOW_BORDER|ZR_WINDOW_MOVEABLE|ZR_WINDOW_CLOSEABLE);
{
    /* fixed widget pixel width */
    zr_layout_row_static(&ctx, 30, 80, 1);
    if (zr_button_text(&ctx, "button", ZR_BUTTON_DEFAULT)) {
        /* event handling */
    }

    /* fixed widget window ratio width */
    zr_layout_row_dynamic(&ctx, 30, 2);
    if (zr_option(&ctx, "easy", op == EASY)) op = EASY;
    if (zr_option(&ctx, "hard", op == HARD)) op = HARD;

    /* custom widget pixel width */
    zr_layout_row_begin(&ctx, ZR_STATIC, 30, 2);
    {
        zr_layout_row_push(&ctx, 50);
        zr_label(&ctx, "Volume:", ZR_TEXT_LEFT);
        zr_layout_row_push(&ctx, 110);
        zr_slider_float(&ctx, 0, &value, 1.0f, 0.1f);
    }
    zr_layout_row_end(&ctx);
}
zr_end(ctx);

**Comment by vurtun** [comment]
So as far as I can understand your problem is that you don't want to use OpenGL to draw the GUI but instead just want use what SDL provides. This shouldn't be as big of a problem, at least if you already have SDL drawing capabilities for basic shapes and text. Maybe you should have a look at `demo/x11/xlib.c` which implements a non OpenGL based implementation which only uses basic shapes and text drawing but only for X11 (You probably should not have a big problem translating the X11 drawing calls to SDL). If you tried and still are not able to get it working than I can spend some time implementing a demo.
