### ISSUE TITLE
Rendering differences

### ISSUE THREAD

**Issue by fr500** [vurtun/zahnrad#52]
I think this would be better for a forum since I don't think it's really an issue, just a difference, but it's the only place were I can ask so here it is.

I have noticed some subtle differences in the GLFW and Allegro samples, I was wondering if it was possible to have a similar end result on GL (Allegro looks better, sharper in my opinion but opinions are subjective)

Check the uppercase E in node editor

Allegro:
![screenshot 2016-02-25 20 02 35](https://cloud.githubusercontent.com/assets/1721040/13339997/c36af974-dbfa-11e5-8f9c-b0f26f321b1e.png)

GLFW:
![screenshot 2016-02-25 20 02 39](https://cloud.githubusercontent.com/assets/1721040/13339998/c36d3680-dbfa-11e5-8d18-f896c84a3287.png)

It's very subtle but the colors look better and the fonts look better too.
We're using this for RetroArch as I mentioned before and I felt the text was a bit blurry.
![screenshot 2016-02-25 20 08 09](https://cloud.githubusercontent.com/assets/1721040/13340090/82cdc850-dbfb-11e5-8a31-aff2d367267e.png)

**Comment by dumblob** [comment]
First, I think if a user has any question or comment which is not chat, then it's definitely an issue and fits here, so no forum is needed as for chat Twitter is used ;) So, thank you for reporting this.

I've taken a look at the pictures you provided and I have quite reversed subjective feeling about Allegro and GLFW based on your pictures. Namely that GLFW is sharper and better-looking ;)

Anyway, it seems both libraries work with text a bit differently, so I'd say it's just about settings of each library, nothing else. What do you think @vurtun ?

**Comment by vurtun** [comment]
> I think this would be better for a forum since I don't think it's really an issue, just a difference, but it's the only place were I can ask so here it is.

Like @dumblob said and I would agree I think it is perfectly fine to use the issue tracker for discussions about anything related to zahnrad. I personally think it would be a waste to use the issue tracker just for bugs. Quite the opposite actually, I am currently thinking about using it more like for discussing bigger changes in the library just like the one I am currently doing and maybe ask for more feedback. 
At least on the technical side Githubs Markdown combined with its preview feature with image and gif support seems sufficient to me and what I normally would want or use in a forum. 

So if anyone is reading this and hesitated to write an issue because it was not directly about an "issue" feel free to create it. I am open for any kind of suggestions, ideas or alternative design decisions. If you work on something alone for quite some time you get tunnel vision and often obvious solutions, problems are completely out of your vision and you need someone to point out the obvious again.

> I have noticed some subtle differences in the GLFW and Allegro samples, I was wondering if it was possible to have a similar end result on GL (Allegro looks better, sharper in my opinion but opinions are subjective)

OK this is embarrassing but for me they look absolutely the same. Which is mainly because of my shitty monitor which at this point is quite old and most colors are already wrong. But what I can make out is that the font in GLFW seem to me more sharp than the one in Allegro.

> We're using this for RetroArch as I mentioned before and I felt the text was a bit blurry.
If the text is a blit blurry try to play with `oversample_h` and `oversample_v` which can be found in `struct zr_font_config` inside the demo function `font_bake_and_upload`. For example an oversample of `oversample_h = 2` and `oversample_v = 2` requires 4x the memory but can lead to better quality. You could also use bilinear filtering for additional quality. More about oversampling can be found here: https://github.com/nothings/stb/tree/master/tests/oversample.

**Comment by fr500** [comment]
Hey, thanks for the feedback
Actually I tried that but I didn't see a notable difference but the bilinear idea gave me a hint. I changed the texture filter to nearest and everything is sharp and nice now (at least better suited to my taste). It's a very subtle difference but it's exactly what I was talking about.

![screenshot 2016-02-26 20 27 52](https://cloud.githubusercontent.com/assets/1721040/13374323/4b7185f4-dd4f-11e5-9a85-fee2adf00f5a.png)
![screenshot 2016-02-27 12 34 24](https://cloud.githubusercontent.com/assets/1721040/13374324/4cde54e4-dd4f-11e5-8f86-f10fe2381eb4.png)

**Comment by vurtun** [comment]
> Actually I tried that but I didn't see a notable difference except for some alignment issues... some letters were positioned oddly with oversample cranked up.

I will take a look and put the alignment issue on my todo list, but it is good to know that something is wrong. I remember the last time I tested it (which is quite some time ago) it worked fine but due to the many changes I probably introduced some bugs. 

> The bilinear idea gave me a hint. I changed the texture filter to nearest and everything is sharp and nice now (at least better suited to my taste). It's a very subtle difference but it's exactly what I was talking about.

Good to know and at least for me as well from what I can see in your screenshots it seems like the nearest quality is better. So I will probably change texture filtering inside the OpenGL demos to nearest. Quite happy that this could be solved.

> I'll try to piggyback on our own font rendering code to avoid code duplication, if I manage I'll let you know.

If you use your own font handling than I would recommend defining `ZR_COMPILE_WITH_FONT` as `0` and remove `stb_truetype` and `stb_rect_pack` since they are only needed for the default font handling module. This brings the library down to just two files which is always easier to manage. 
As for using your own font rendering code I would recommend looking at functions `zr_font_query_font_glyph` and maybe `zr_font_text_width`.
