### ISSUE TITLE
Clicks registering while resizing

### ISSUE THREAD

**Issue by fr500** [vurtun/zahnrad#58]
Don't know if this is a bug per-se or some error in my implementation, I tried to reproduce on the demos a lot and only managed once to get a click to register.
Basically it seems that resizing a window causes some unintended clics on some elements when you hover over them (or the place were the elements would be after resizing.

![resize](https://cloud.githubusercontent.com/assets/1721040/13517429/7e2b75ae-e191-11e5-9295-53b8834dd80f.gif)

May be related to this other issue? https://github.com/vurtun/zahnrad/issues/54
I'll revert this
win->flags &= ~(zr_flags)ZR_WINDOW_ROM

In my code and do some more testing

**Comment by fr500** [comment]
Hmm no it seems it's not related to that, tried reverting that change and no difference.
Actually it seems to be just what I implied, a click is being registered while dragging, maybe my pointer implementation causes this?

It became less obvious once I added some extra padding.

**Comment by vurtun** [comment]
I am not 100% what the .gif shows but from what I understand is that if you scale a window and have a window underneath or next to it and it registers a click on that window? Does this behavior occur if you let go of the mouse button or even if you just move the pressed mouse? If the click happens while the mouse is moved and button is being pressed then it sounds like a bug that makes no sense at all to me since mouse movement should not cause clicks (only button up does). 

What maybe could happen with flag: win->flags &= ~(zr_flags)ZR_WINDOW_ROM is that if a window is scaled and right next to the currently scaled window then the other window could get focus and if you release the mouse button than a click is registered (clicks are registered on button up for touch device, you could change that to button down as a possible solution).

So what I would ask you if you could test again with clicks happening on button down instead of button up. As far as I remember you only have to change `zr_input_is_mouse_click_in_rect` in `zahnrad.c:6462` from 
```c
return (zr_input_has_mouse_click_down_in_rect(i, id, b, zr_false) && btn->clicked) ? zr_true : zr_false;
```
to
```c
return (zr_input_has_mouse_click_down_in_rect(i, id, b, zr_true) && btn->clicked) ? zr_true : zr_false;
```
If that does not bring a solutions then it would be nice if you could exactly describe to me what you are doing and how and when this behavior occurs since I am not able to replicate the issue in the demo.

**Comment by fr500** [comment]
Oh... I thought it would be pretty obvious.

No,  it's not clicking the window underneath,  it's clicking on the
saturation property.

I'll test the code change you mentioned ASAP

**Comment by vurtun** [comment]
Ah OK I absolutely did not see that. That look like a bug I will test it and see if I can fix it. Seems like something is quite right. Does this only happen with properties or also with other widgets?, that would at least narrow down the problem space.

**Comment by vurtun** [comment]
Ok quick update. I found the problem and fixed it. I only check for a click in the property but the click could have been in the past and it would still register it as a click inside the property and therefore cause the property to change its values. I fixed to only activate if the click was on that frame and therefore hopefully fixed the bugged property behavior.

**Comment by fr500** [comment]
thank you very much!
fixed
